### PR TITLE
Update and rename cgdsMigration.Rmd to cgdsrMigration.Rmd

### PR DESCRIPTION
**Pull request by kmezhoud**
get Studies, Cases/Samples, Clinical Data, mRNA, mutations, endpoints

### CODE REVIEW

**Comment by LiNk-NY** [comment]
Hi Karim, @kmezhoud 
It is hard to compare the differences between the files. I will rename first to see if that helps.

**Comment by kmezhoud** [comment]
Hi Marcel, @LiNk-NY 
Sure! It will easiest to run the .Rmd file locally and show the html output.
GitHub cannot do that for us. 
Karim

**Comment by LiNk-NY** [comment]
Hi Karim, @kmezhoud 
Can you merge the `devel` branch into yours?

**Comment by LiNk-NY** [comment]
Hi Karim, @kmezhoud 
Can you merge the `devel` branch into yours?

**Comment by kmezhoud** [comment]
Hi Marcel, @LiNk-NY ,
I will do that.
But I will have  the same  9 conflicts, which are the Mains differences between files.
To solve the conflicts, just delete/remove one PART of two choices. 

```
<<<<<<<<branch1
PART 1:  SUGGESTED/NEW VERSION
=============
PART 2:  ACTUAL/OLD VERSION
>>>>>>>>branch2
```
Example of the title conflict:

```
<<<<<<< devel
title: "Migrating from cgdsr to cBioPortalData"
=======
title: "cgdsr Migration"
>>>>>>> devel
```
To resolve this conflict just leave the desired title and delete the rest.
During resolving conflict you will be able to compare the difference between files. 

Karim

**Comment by LiNk-NY** [comment]
Hi Karim, @kmezhoud 

It may be easier to create a new branch based on the `devel` branch and add copy and paste your changes to the vignette.
The multiple renames threw off the `git diff` print out that you could have saved (rather than copying an pasting).
It would then be easier to see the differences in the vignette after you create a new pull request. 
Thank you!

Best,
Marcel

**Pull request closed without merging**
